import React from 'react';

const PresaleRuleContent = () => {
  return (
    <div>
      <h2>Privacy Policy</h2>
      <p>
        In order to protect the legitimate rights and interests of users participating in the presale and maintain the normal operation order of the presale, the rules are formulated in accordance with relevant agreements and rules of national laws and regulations.
      </p>
      <h3>Chapter 1: Definition</h3>
      <ul>
        <li><strong>1.1 Presale definition:</strong> refers to a sales model in which a merchant provides a product or service plan, gathers consumer orders through presale product tools, and provides goods and/or services to consumers according to prior agreement.</li>
        <li><strong>1.2 The presale model is a "deposit" model:</strong> "Deposit" refers to a fixed amount of presale commodity price pre-delivered. “The deposit” can participate in small games and have the opportunity to win more deposits. The deposit can be directly exchanged for commodities. The deposit is not redeemable.</li>
        <li><strong>1.3 Presale products:</strong> refers to the products released by merchants using presale product tools. Only the presale words are marked on the product title or product details page, and the products that do not use the presale product tools are not presale products.</li>
        <li><strong>1.4 Presale system:</strong> Refers to the system product tools provided to support merchants for presale model sales.</li>
        <li><strong>1.5 Presale commodity price:</strong> refers to the selling price of presale commodity. The price of presale goods is composed of two parts: deposit and final payment.</li>
        <li><strong>1.6 Presale deposit:</strong> Refers to a certain amount of money that consumers pay in advance when purchasing presale goods, which is mainly used as a guarantee to purchase presale goods and determine the purchase quota.</li>
        <li><strong>1.7 Presale final payment:</strong> refers to the amount of money that the consumer still has to pay after the presale commodity price minus the deposit.</li>
      </ul>

      <h3>Chapter 2: Presale management specifications</h3>
      <h4>2.1 Commodity management</h4>
      <ul>
        <li><strong>2.1.1 Presale deposit time:</strong> up to 7 days can be set.</li>
        <li><strong>2.1.2 Presale final payment time:</strong> The start time of the final payment is within 7 days.</li>
        <li><strong>2.1.3</strong> During the presale of commodities, the system does not support merchants to modify the price of pre-sold commodities (including deposits and balances), but the amount of remaining commodity inventory can be modified according to the actual situation of inventory.</li>
        <li><strong>2.1.4</strong> To avoid unnecessary disputes, If the presale product is a customized product, the merchant should clearly inform the consumer on the product page of the production cycle and delivery time of the product, and contact the consumer to confirm the delivery standard, delivery time, etc.</li>
        <li><strong>2.1.5</strong> For customized products, the merchant has not agreed with the consumer on the delivery time and delivery standard, the delivery standard proposed by the consumer is unclear or conflicts and after the merchant places an order, he(she) starts production and delivery without confirming with the consumer, if the consumer initiates a dispute as a result, the platform will treat it as a normal delivery time limit order fulfillment.</li>
      </ul>

      {/* More content can be added similarly... */}

      <h4>Explanation</h4>
      <p>Mall transaction mode:</p>
      <ul>
        <li>The deposit purchase mode will freeze the customer's deposit, and the customer will take delivery after completing the final payment within 7 days.</li>
        <li>The red envelope can be withdrawn directly, so that instead of losing money, the customer has added a commodity order generated by a deposit.</li>
      </ul>

      <p>
        <strong>Note:</strong> I have carefully read all contents of this presale management rule, Risk Disclosure Agreement, and Risk Agreement and I am agreed to continue with my own risk.
      </p>
    </div>
  );
};

export default PresaleRuleContent;
